# Generated by Django 5.2.5 on 2025-11-20 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHierarchyCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Location Hierarchy Caches',
            },
        ),
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cache_data', models.JSONField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Caches',
                'indexes': [models.Index(fields=['cache_key', 'expires_at'], name='analytics_d_cache_k_ad987b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthCenterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('elevation_m', models.FloatField(blank=True, help_text='Elevation in meters', null=True)),
                ('slope_percent', models.FloatField(blank=True, help_text='Slope percentage (0-100)', null=True)),
                ('slope_degrees', models.FloatField(blank=True, help_text='Slope in degrees', null=True)),
                ('geojson_geometry', models.JSONField(blank=True, help_text='GeoJSON Point or Polygon', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_centres', to='accounts.sector')),
            ],
            options={
                'verbose_name': 'Health Centre Location',
                'verbose_name_plural': 'Health Centre Locations',
                'ordering': ['sector', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MalariaAnalyticsAggregated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_tests', models.IntegerField(default=0)),
                ('positive_cases', models.IntegerField(default=0)),
                ('negative_cases', models.IntegerField(default=0)),
                ('positivity_rate', models.FloatField(default=0.0)),
                ('negativity_rate', models.FloatField(default=0.0)),
                ('female_tests', models.IntegerField(default=0)),
                ('female_positive', models.IntegerField(default=0)),
                ('female_positivity_rate', models.FloatField(default=0.0)),
                ('male_tests', models.IntegerField(default=0)),
                ('male_positive', models.IntegerField(default=0)),
                ('male_positivity_rate', models.FloatField(default=0.0)),
                ('under_5_tests', models.IntegerField(default=0)),
                ('under_5_positive', models.IntegerField(default=0)),
                ('over_5_tests', models.IntegerField(default=0)),
                ('over_5_positive', models.IntegerField(default=0)),
                ('temperature_avg', models.FloatField(blank=True, null=True)),
                ('precipitation_mm', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('data_completeness', models.FloatField(default=100.0)),
                ('is_provisional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='analytics_dashboard.healthcenterlocation')),
            ],
            options={
                'ordering': ['-date', '-year', 'health_centre'],
            },
        ),
        migrations.AddIndex(
            model_name='healthcenterlocation',
            index=models.Index(fields=['code'], name='analytics_d_code_cabe1c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcenterlocation',
            index=models.Index(fields=['sector'], name='analytics_d_sector__529e03_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcenterlocation',
            index=models.Index(fields=['is_active'], name='analytics_d_is_acti_8df58a_idx'),
        ),
        migrations.AddIndex(
            model_name='malariaanalyticsaggregated',
            index=models.Index(fields=['year', 'month'], name='analytics_d_year_53d467_idx'),
        ),
        migrations.AddIndex(
            model_name='malariaanalyticsaggregated',
            index=models.Index(fields=['health_centre', 'year'], name='analytics_d_health__9aeaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='malariaanalyticsaggregated',
            index=models.Index(fields=['date'], name='analytics_d_date_188b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='malariaanalyticsaggregated',
            index=models.Index(fields=['positivity_rate'], name='analytics_d_positiv_7c7987_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='malariaanalyticsaggregated',
            unique_together={('health_centre', 'year', 'month', 'date')},
        ),
    ]
