# Generated by Django 5.2.5 on 2025-11-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified_customuser_otp_code_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_created',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'email_verified'], name='accounts_cu_email_02b8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username', 'email_verified'], name='accounts_cu_usernam_b9a9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['otp_code', 'otp_created'], name='accounts_cu_otp_cod_6298e7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['province', 'district', 'sector'], name='accounts_cu_provinc_c84435_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['province', 'name'], name='accounts_di_provinc_fdd9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='accounts_di_name_8a503f_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['name'], name='accounts_pr_name_8058bc_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['district', 'name'], name='accounts_se_distric_a51a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['name'], name='accounts_se_name_4a5ba4_idx'),
        ),
    ]
